inventory/inventory/urls.py
from django.conf.urls import include
from inventory.views import IndexView
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products'))
]

inventory/products/urls.py
from django.urls import path
from . views import AddProductStock, AddProductView, FetchProductCode, FetchProductInformation, ProductList, FetchProductType, ProductTypeList, ManageStockView, ProductListView, ProductTypeListView

app_name = 'products'

urlpatterns = [
    # Static urls
    path('product-list/', ProductListView.as_view(), name='product-list'),
    path('add-product/', AddProductView.as_view(), name='add-product'),
    path('manage-stock/', ManageStockView.as_view(), name='manage-stock'),
    path('product-type-list/', ProductTypeListView.as_view(), name='product-type-list'),

    # AJAX/ REST urls
    path('fetch-product-list/', ProductList.as_view(), name='fetch-product-list'),
    path('fetch-product-type-list/', ProductTypeList.as_view(), name='fetch-product-type-list'),
    path('fetch-product-type/', FetchProductType.as_view(), name='fetch-product-type'),
    path('submit-product/', ProductList.as_view(), name='submit-product'),
    path('fetch-product-code/', FetchProductCode.as_view(), name='fetch-product-code'),
    path('fetch-product-information/', FetchProductInformation.as_view(), name='fetch-product-information'),
    path('submit-product-stock/', AddProductStock.as_view(), name='submit-product-stock'),
]

inventory/products/models.py
from django.db import models

# Create your models here.

inventory/products/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from rest_framework.views import APIView
from .serializers import ProductSerializer, ProductTypeSerializer
from django.views.generic import ListView, View, CreateView, TemplateView
from core.models import Product, ProductManagement, ProductType, StockManagement
from rest_framework.response import Response
from rest_framework import status
from django.http import JsonResponse
from django.db.models import Q
import strings
from checkdigit import isbn


# Create your views here.
class ProductListView(ListView):
    template_name = 'products/product_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.all()


class AddProductView(TemplateView):
    template_name = 'products/add_product.html'
    queryset = Product.objects.all()


class ManageStockView(TemplateView):
    template_name = 'products/manage_stock.html'


class ProductTypeListView(ListView):
    template_name = 'products/product_type_list.html'
    context_object_name = 'product_types'

    def get_queryset(self):
        return ProductType.objects.all()


class ProductList(APIView):
    permission_classes = []

    def post(self, request):
        code = request.POST.get('code')
        name = request.POST.get('name')
        category = request.POST.get('category')
        type = request.POST.get('type')
        unit_price = request.POST.get('unit_price')
        size_list = request.POST.getlist('size_list[]', None)

        if code:
            if not Product.objects.filter(product_code=code):
                product = Product.objects.create(
                    product_code=code,
                    product_name=name,
                    category=category,
                    type=ProductType.objects.get(id=type)
                )

                for size in size_list:
                    StockManagement.objects.create(
                        product=product,
                        size=size,
                        unit_price=unit_price
                    )

                data = {
                    'status': status.HTTP_201_CREATED
                }
            else:
                data = {
                    'status': status.HTTP_409_CONFLICT
                }
        else:
            data = {
                'status': status.HTTP_400_BAD_REQUEST
            }

        return JsonResponse(data, safe=False)

    def get(self, request):
        # From datatable pipeline function
        draw = int(request.GET.get('draw', 0))
        order_col_i = int(request.GET.get('order[0][column]', 0))
        order_dir = request.GET.get('order[0][dir]', None)
        start_i = int(request.GET.get('start', 0))
        length = int(request.GET.get('length', 0))
        search_key = request.GET.get('search[value]', '')

        recordsTotal = Product.objects.all().count()
        products, recordsFiltered = self.get_filtered_product(
            start_i, length, order_col_i, order_dir, search_key)

        data = []
        for product in products:
            data.append({'id': product.id, 'product_name': product.product_name, 'type': product.type.type_name, 'category': product.category,
                        'product_code': product.product_code, 'stock': product.total_stock, 'unit_price': product.unit_price})

        return JsonResponse({'draw': draw, 'recordsTotal': recordsTotal, 'recordsFiltered': recordsFiltered, 'data': data})

    def get_filtered_product(self, start_i, length, order_col_i, order_dir, search_key):
        """
        Parameters:
            start_i: int
                Row start index
            length: int
                Number of rows to fetch
            order_col_i: int
                Column index by which ordering will be done
            order_dir: str
                Order direction (asc or desc)
            search_key: str
                Search keyword
        """

        columns = ['product_name', 'product_code', 'unit_price', 'total_stock']
        order_col = columns[order_col_i]
        if order_dir == 'desc':
            order_col = '-' + order_col

        if search_key:
            products = Product.objects.filter(Q(product_name__icontains=search_key) |
                                              Q(product_code__icontains=search_key) |
                                              Q(unit_price__icontains=search_key) |
                                              Q(total_stock__icontains=search_key)).distinct().order_by(order_col)
            filter_length = products.count()
        else:
            products = Product.objects.all().order_by(order_col)
            filter_length = products.count()

        products = products[start_i:start_i+length]

        return products, filter_length


class ProductTypeList(APIView):
    permission_classes = []

    def post(self, request):
        type_name = request.POST.get('type_name')

        if type_name:
            if not ProductType.objects.filter(type_name=type_name).exists():
                ProductType.objects.create(
                    type_name=type_name
                )
                data = {
                    'status': status.HTTP_201_CREATED
                }

            else:
                data = {
                    'status': status.HTTP_409_CONFLICT
                }
        else:
            data = {
                'status': status.HTTP_400_BAD_REQUEST
            }

        return JsonResponse(data, safe=False)

    def get(self, request):
        # From datatable pipeline function
        draw = int(request.GET.get('draw', 0))
        order_col_i = int(request.GET.get('order[0][column]', 0))
        order_dir = request.GET.get('order[0][dir]', None)
        start_i = int(request.GET.get('start', 0))
        length = int(request.GET.get('length', 0))
        search_key = request.GET.get('search[value]', '')

        recordsTotal = ProductType.objects.all().count()
        product_types, recordsFiltered = self.get_filtered_product_type(
            start_i, length, order_col_i, order_dir, search_key)

        data = []
        for product_type in product_types:
            if Product.objects.filter(type=product_type.id).exists():
                product = Product.objects.get(type=product_type.id)
                if StockManagement.objects.filter(product=product).exists():
                    stock_managements = StockManagement.objects.filter(
                        product=product)
                    stock = 0
                    sold = 0
                    for stock_management in stock_managements:
                        stock += stock_management.stock
                        sold += stock_management.sold
            else:
                stock = 0
                sold = 0

            data.append(
                {'id': product_type.id, 'type_name': product_type.type_name, 'stock': stock, 'sold': sold})

        return JsonResponse({'draw': draw, 'recordsTotal': recordsTotal, 'recordsFiltered': recordsFiltered, 'data': data})

    def get_filtered_product_type(self, start_i, length, order_col_i, order_dir, search_key):
        """
        Parameters:
            start_i: int
                Row start index
            length: int
                Number of rows to fetch
            order_col_i: int
                Column index by which ordering will be done
            order_dir: str
                Order direction (asc or desc)
            search_key: str
                Search keyword
        """

        columns = ['id']
        order_col = columns[order_col_i]
        if order_dir == 'desc':
            order_col = '-' + order_col

        if search_key:
            product_types = ProductType.objects.filter(Q(product_name__icontains=search_key) |
                                                       Q(product_code__icontains=search_key) |
                                                       Q(stock_management__unit_price__icontains=search_key) |
                                                       Q(stock_management__stock__icontains=search_key)).order_by(order_col)
            filter_length = product_types.count()
        else:
            product_types = ProductType.objects.all().order_by(order_col)
            filter_length = product_types.count()

        product_types = product_types[start_i:start_i+length]

        return product_types, filter_length


class FetchProductType(APIView):
    permission_classes = []

    def get(self, request):
        types = ProductType.objects.all()
        serializer = ProductTypeSerializer(types, many=True)

        return JsonResponse(serializer.data, safe=False)


class FetchProductCode(APIView):
    permission_classes = []

    def get(self, request):
        term = request.GET.get('term')

        if term:
            if term.isdigit():
                products = Product.objects.filter(product_code=term)
            else:
                return JsonResponse({'status': status.HTTP_404_NOT_FOUND})
        else:
            products = Product.objects.all()

        data = []
        for product in products:
            data.append(
                {'id': product.id, 'product_code': product.product_code})

        return JsonResponse(data, safe=False)


class FetchProductInformation(APIView):
    permission_classes = []

    def get(self, request):
        product_code = request.GET.get('product_code')

        if product_code:
            if Product.objects.filter(product_code=product_code).exists():
                product = Product.objects.get(product_code=product_code)
                product_name = product.product_name
                category = product.category
                type = product.type.type_name
                size_list = []
                stock_managements = StockManagement.objects.filter(
                    product=product)
                for stock_management in stock_managements:

inventory/products/templates/products/add_product.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Add Product {% endblock title %}

{% block stylesheets %}
{{block.super}}
<link rel="stylesheet" href="{% static 'custom/products/css/master.css' %}">
<link rel="stylesheet" href="{% static 'custom/css/buttons.css' %}">
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
    <div class="">
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 center-margin">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>
                            <span class="fa fa-chevron-left mr-2" aria-hidden="true" data-toggle="tooltip"
                                data-placement="top" title="Back" onClick="javascript:history.go(-1);"></span> Add
                            Product
                        </h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div id="product-add-success-alert" role="alert"></div>
                        <div id="product-add-error-alert" role="alert"></div>
                        <div id="product-add-warning-alert" role="alert"></div>
                        <div id="product-add-info-alert" role="alert"></div>
                        <fieldset class="custom-legend">
                            <legend><small>Product Informations</small></legend>
                            <div class="item form-group">
                                <label class="col-form-label col-md-4 col-sm-4 label-align">Code</label>
                                <div class="col-md-4 col-sm-4">
                                    <input type="text" class="form-control" name="product-code">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="col-form-label col-md-4 col-sm-4 label-align">Name</label>
                                <div class="col-md-4 col-sm-4">
                                    <input type="text" class="form-control" name="product-name">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="col-form-label col-md-4 col-sm-4 label-align">Category</label>
                                <div class="col-md-4 col-sm-4">
                                    <select class="custom-select form-select" name="product-category">
                                        <option value="None">-- Select any --</option>
                                        <option value="Male">Male</option>
                                        <option value="Female">Female</option>
                                        <option value="Child">Child</option>
                                    </select>
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="col-form-label col-md-4 col-sm-4 label-align">Type</label>
                                <div class="col-md-4 col-sm-4">
                                    <select class="form-select" name="product-type">
                                        <option value="None">-- Select any --</option>
                                    </select>
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="col-form-label col-md-4 col-sm-4 label-align">Unit Price (৳)</label>
                                <div class="col-md-4 col-sm-4">
                                    <input type="number" class="form-control" name="product-unit-price">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="col-form-label col-md-4 col-sm-4 label-align">Size</label>
                                <div class="col-md-4 col-sm-4">
                                    <input type="number" class="form-control" name="product-size">
                                </div>
                                <div class="col-md-3 col-sm-3">
                                    <i id="add-size" class="fas fa-plus-circle fa-2x mt-1 icon-btn-add"
                                        data-toggle="tooltip" data-placement="top" title="Add Another"></i>
                                </div>
                            </div>
                            <input type="hidden" name="size-input-count">
                            <div id="multiple-size-container"></div>
                            <div class="item form-group">
                                <div class="col-md-4 col-sm-4 offset-md-4">
                                    <button type="button" class="btn btn-cancel btn-sm" name="button">Cancel</button>
                                    <button id="add-product-submit" type="button" class="btn btn-success btn-sm"
                                        name="button">Submit</button>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block javascripts %}
{{block.super}}
<script>
    $(document).ready(function () {
        $("input[name=size-input-count]").val(0)
        // successMessage('product-add-success-alert', 'Successfully added new product.', '{% url "products:product-list" %}', 'Product List');
        // errorMessage('product-add-error-alert', 'Something went wrong.')
        // warningMessage('product-add-warning-alert', 'This is a warning alert.')
        // infoMessage('product-add-info-alert', 'This is an info alert.')
        fetchProductType()
    });

    $("#add-size").click(function () {
        var sizeDivCount = $("#multiple-size-container > div").length;
        var sizeInputHtml = `<div class="item form-group size-input" id="size-input-${sizeDivCount + 1}">
                                <label class="col-form-label col-md-4 col-sm-4 label-align">Size</label>
                                <div class="col-md-4 col-sm-4">
                                    <input type="number" class="form-control" name="product-size-${sizeDivCount + 1}">
                                </div>
                                <div class="col-md-3 col-sm-3">
                                    <i id="remove-size-input-${sizeDivCount + 1}" onClick="removeDiv(${sizeDivCount + 1})" class="fas fa-minus-circle fa-2x mt-1 icon-btn-remove" data-toggle="tooltip"
                                    data-placement="top" title="Remove"></i>
                                </div>
                            </div>`;
        $("#multiple-size-container").append(sizeInputHtml);
        $("input[name=size-input-count]").val(sizeDivCount + 1);
        $('[data-toggle="tooltip"]').tooltip();
    })

    function removeDiv(index) {
        var prevDivCount = $("input[name=size-input-count]").val();
        $("input[name=size-input-count]").val(prevDivCount - 1);
        var newDivCount = $("input[name=size-input-count]").val();
        $("#size-input-" + index).remove();
        reIndexInput(newDivCount, "size-input-", "size-input")
        $('[data-toggle="tooltip"], .tooltip').tooltip('hide');
    }

    function fetchProductType() {
        $.ajax({
            type: 'GET',
            url: '{% url "products:fetch-product-type" %}',
            data: {},
            dataType: 'json',
            success: function (data) {
                if (data.length > 0) {
                    for (let i = 0; i < data.length; i++) {
                        $("select[name=product-type]").append(`<option value="${data[i].id}">${data[i].type_name}</option>`);
                    }
                }
            }
        })
    }

    $("#add-product-submit").click(function () {
        var code = $("input[name=product-code]").val();
        var name = $("input[name=product-name]").val();
        var category = $("select[name=product-category] option:selected").val();
        var type = $("select[name=product-type] option:selected").val();
        var price = $("input[name=product-unit-price").val();
        var sizeInputCount = $("input[name=size-input-count]").val();
        var sizeArr = [];
        var size = $("input[name=product-size]").val()
        sizeArr.push(size);

        for (let i = 0; i < sizeInputCount; i++) {
            sizeArr.push($(`input[name=product-size-${i + 1}]`).val());
        }

        console.log(sizeArr);

        $.ajax({
            type: 'POST',
            url: '{% url "products:submit-product" %}',
            data: {
                'code': code,
                'name': name,
                'category': category,
                'type': type,
                'unit_price': price,
                'size_list': sizeArr,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            dataType: 'json',
            success: function (data) {
                if (data.status == 201) {
                    $("input[name=product-code]").val("");
                    $("input[name=product-name]").val("");
                    $("select[name=product-category]").val("None");
                    $("select[name=product-type]").val("None");
                    $("input[name=product-unit-price").val("");
                    $("input[name=product-size]").val("");
                    $("#multiple-size-container").empty();
                    successMessage('product-add-success-alert', 'Successfully added new product.', '{% url "products:product-list" %}', 'Product List');
                }
            }
        })
    })
</script>
{% endblock javascripts%}

inventory/products/templates/products/manage_stock.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Manage Stock {% endblock title %}

{% block stylesheets %}
{{block.super}}
<link rel="stylesheet" href="{% static 'custom/products/css/master.css' %}">
<link rel="stylesheet" href="{% static 'custom/css/buttons.css' %}">
<!-- Select2 -->
<link href="{% static 'vendors/select2-4.0.13/dist/css/select2.min.css' %}" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
    <div class="">
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 center-margin">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>
                            <span class="fa fa-chevron-left mr-2" aria-hidden="true" data-toggle="tooltip"
                                data-placement="top" title="Back" onClick="javascript:history.go(-1);"></span>
                            Add Stock
                        </h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div id="stock-add-success-alert" role="alert"></div>
                        <div id="stock-add-error-alert" role="alert"></div>
                        <div id="stock-add-warning-alert" role="alert"></div>
                        <div id="stock-add-info-alert" role="alert"></div>
                        <fieldset class="custom-legend">
                            <legend><small>Product Stock Informations</small></legend>
                            <div class="item form-group">
                                <label class="col-form-label col-md-4 col-sm-4 label-align">Code</label>
                                <div class="col-md-4 col-sm-4">
                                    <select class="form-select" type="text" name="product-code"></select>
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="col-form-label col-md-4 col-sm-4 label-align">Name</label>
                                <div class="col-md-4 col-sm-4">
                                    <input type="text" class="form-control" disabled name="product-name">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="col-form-label col-md-4 col-sm-4 label-align">Category</label>
                                <div class="col-md-4 col-sm-4">
                                    <input type="text" class="form-control" disabled name="product-category">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="col-form-label col-md-4 col-sm-4 label-align">Type</label>
                                <div class="col-md-4 col-sm-4">
                                    <input type="text" class="form-control" disabled name="product-type">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="col-form-label col-md-4 col-sm-4 label-align">Size</label>
                                <div class="col-md-4 col-sm-4">
                                    <select class="custom-select form-select" type="text" disabled name="product-size">
                                        <option value="">-- Select any --</option>
                                    </select>
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="col-form-label col-md-4 col-sm-4 label-align">Quantity</label>
                                <div class="col-md-4 col-sm-4">
                                    <input type="number" class="form-control" disabled name="product-quantity">
                                </div>
                            </div>
                            <div class="item form-group">
                                <div class="col-md-4 col-sm-4 offset-md-4">
                                    <button type="button" class="btn btn-cancel btn-sm" name="button">Cancel</button>
                                    <button id="stock-add-submit-btn" type="button" class="btn btn-success btn-sm" name="button">Submit</button>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block javascripts %}
{{block.super}}
<!-- Select2 -->
<script src="{% static 'vendors/select2-4.0.13/dist/js/select2.min.js' %}"></script>
<script>
    $(document).ready(function () {

    });

    $("select[name='product-code']").select2({
        ajax: {
            url: '{% url "products:fetch-product-code" %}',
            datatype: 'json',
            data: function (params) {
                var query = {
                    term: params.term,
                }

                return query;
            },
            processResults: function (data) {
                return {
                    results: $.map(data, function (item) {
                        return { id: item.id, text: item.product_code }
                    })
                };
            }
        },
        minimumInputLength: 3,
        searchInputPlaceholder: 'Product Code',
        width: '100%',
        theme: "default"
    });

    $("select[name='product-code']").change(function () {
        var productCode = $("select[name='product-code'] option:selected").html();
        $.ajax({
            type: 'GET',
            url: '{% url "products:fetch-product-information" %}',
            data: {
                'product_code': productCode
            },
            datatype: 'json',
            success: function (data) {
                if (data.status == 200) {
                    console.log("## ---- Fetch Product Information ---- ## ---- OK ---- ##", data.status);
                    $("input[name=product-name]").val(data.product_name);
                    $("input[name=product-category]").val(data.category);
                    $("input[name=product-type]").val(data.type);
                    $("select[name=product-size]").prop('disabled', false);
                    $("input[name=product-quantity]").prop('disabled', false);
                    for (let i = 0; i < data.size_list.length; i++) {
                        $("select[name=product-size]").append(`<option value=${data.size_list[i]}>${data.size_list[i]}</option>`)
                    }
                }

                if (data.status == 404) {
                    console.log("## ---- Fetch Product Information ---- ## ---- NOT FOUND ---- ##", data.status);
                }

                if (data.status == 400) {
                    console.log("## ---- Fetch Product Information ---- ## ---- BAD REQUEST ---- ##", data.status);
                }
            }
        })
    })

    $("#stock-add-submit-btn").click(function() {
        var productCode = $("select[name='product-code'] option:selected").html();
        var size = $("select[name=product-size] option:selected").val();
        var quantity = $("input[name=product-quantity]").val();
        $.ajax({
            type: 'POST',
            url: '{% url "products:submit-product-stock" %}',
            data: {
                'product_code': productCode,
                'size': size,
                'quantity': quantity,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            dataType: 'json',
            success: function (data) {
                if (data.status == 201) {
                    console.log("## ---- Stock Submit ---- ## ---- CREATED ---- ##", data.status);
                    successMessage('stock-add-success-alert', 'Successfully added new product stcok.', '{% url "products:product-list" %}', 'Product List');
                    $("input[name=product-name]").val("");
                    $("input[name=product-category]").val("");
                    $("input[name=product-type]").val("");
                    $("select[name=product-size]").val("");
                    $("input[name=product-quantity]").val("");
                    $("select[name=product-code]").val("");
                }

                if (data.status == 404) {
                    console.log("## ---- Stock Submit ---- ## ---- NOT FOUND ---- ##", data.status);
                }

                if (data.status == 400) {
                    console.log("## ---- Stock Submit ---- ## ---- BAD REQUEST ---- ##", data.status);
                }
            }
        })
    })



</script>
{% endblock javascripts%}