inventory/inventory/urls.py
from django.conf.urls import include
from inventory.views import IndexView
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products'))
]

inventory/products/urls.py
from django.urls import path
from . views import AddProductStock, AddProductView, FetchProductCode, FetchProductInformation, ProductList, FetchProductType, ProductTypeList, ManageStockView, ProductListView, ProductTypeListView

app_name = 'products'

urlpatterns = [
    # Static urls
    path('product-list/', ProductListView.as_view(), name='product-list'),
    path('add-product/', AddProductView.as_view(), name='add-product'),
    path('manage-stock/', ManageStockView.as_view(), name='manage-stock'),
    path('product-type-list/', ProductTypeListView.as_view(), name='product-type-list'),

    # AJAX/ REST urls
    path('fetch-product-list/', ProductList.as_view(), name='fetch-product-list'),
    path('fetch-product-type-list/', ProductTypeList.as_view(), name='fetch-product-type-list'),
    path('fetch-product-type/', FetchProductType.as_view(), name='fetch-product-type'),
    path('submit-product/', ProductList.as_view(), name='submit-product'),
    path('fetch-product-code/', FetchProductCode.as_view(), name='fetch-product-code'),
    path('fetch-product-information/', FetchProductInformation.as_view(), name='fetch-product-information'),
    path('submit-product-stock/', AddProductStock.as_view(), name='submit-product-stock'),
]

inventory/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  {% block head %}
  {% block meta %}
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% endblock meta %}

  <title>Inventory Management | {% block title %}{% endblock %}</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" />

  {% block stylesheets %}
  <!-- Bootstrap -->
  <link href="{% static 'vendors/bootstrap-5.0.2/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="{% static 'vendors/fontawesome-5.15.3/css/fontawesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendors/fontawesome-5.15.3/css/all.css' %}" rel="stylesheet">
  <!-- Box Icons -->
  <link href="{% static 'vendors/box-icons/css/boxicons.min.css' %}" rel="stylesheet">
  <!-- bootstrap-daterangepicker -->
  <link href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
  <link href="{% static 'vendors/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}"
    rel="stylesheet">
  <link href="{% static 'vendors/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css' %}" rel="stylesheet">
  {% endblock stylesheets %}

  <!-- Custom Theme Style -->
  <link href="{% static 'custom/css/master.css' %}" rel="stylesheet">
  <!-- Custom button css -->
  <!-- <link href="{% static 'custom/css/buttons.css' %}" rel="stylesheet"> -->
  {% endblock head %}
</head>

<body class="{% block body_class %}nav-md {% endblock body_class %}">
  {% block body %}
  <div class="container body">
    <div class="main_container">

      {% block sidebar %}
      <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
        {% include "sidebar.html" %}
      </div>
      {% endblock sidebar %}

      {% block top_navigation %}
      <div class="top_nav">
        {% include "top_navigation.html" %}
      </div>
      {% endblock top_navigation %}

      {% block content %}
      <!-- {{ content }} -->
      {% endblock content %}

      {% block footer %}
      <footer>
        {% include "footer.html" %}
      </footer>
      {% endblock footer %}

    </div>
  </div>

  {% block javascripts %}
  <!-- jQuery -->
  <script src="{% static 'vendors/jquery-3.5.1/dist/jquery.js' %}"></script>
  <!-- Popper -->
  <script src="{% static 'vendors/popper/popper.min.js' %}"></script>
  <!-- Tooltip -->
  <script src="{% static 'vendors/tooltip/tooltip.min.js' %}"></script>
  <!-- Bootstrap -->
  <script src="{% static 'vendors/bootstrap-5.0.2/js/bootstrap.bundle.min.js' %}"></script>
  <!-- Moment -->
  <script src="{% static 'vendors/moment-2.27.0/min/moment.min.js' %}"></script>
  <!-- DateJS -->
  <script src="{% static 'vendors/DateJS/build/date.js' %}"></script>
  <!-- bootstrap-daterangepicker -->
  <script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
  <!-- bootstrap-datetimepicker -->
  <script src="{% static 'vendors/bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js' %}"></script>
  <!-- Box Icons -->
  <script src="{% static 'vendors/box-icons/dist/boxicons.js' %}"></script>

  <script type="text/javascript">
    // Form messages
    function errorMessage(divId, message) {
      $("#" + divId).empty();
      $("#" + divId).addClass("alert alert-danger alert-dismissible");
      $("#" + divId).append(`<i class="fas fa-exclamation-circle fa-lg"></i>`)
      $("#" + divId).append(`<strong> Oh Snap!</strong> ${message}`);
      $("#" + divId).append(`<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>`);
    }

    function successMessage(divId, message, link, linkMessage) {
      $("#" + divId).empty();
      $("#" + divId).addClass("alert alert-success alert-dismissible");
      $("#" + divId).append(`<i class="fas fa-check-circle fa-lg"></i>`);
      
      if (link) {
        $("#" + divId).append(`<strong> Well Done!</strong> ${message} See <a href="${link}" class="alert-link"> ${linkMessage}. </a>`);
      } else {
        $("#" + divId).append(`<strong> Well Done!</strong> ${message}`);
      }                
      
      $("#" + divId).append(`<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>`);
    }

    function warningMessage(divId, message) {
      $("#" + divId).empty();
      $("#" + divId).addClass("alert alert-warning alert-dismissible");
      $("#" + divId).append(`<i class="fas fa-exclamation-circle fa-lg"></i>`);
      $("#" + divId).append(`<strong> Warning!</strong> ${message}`);
      $("#" + divId).append(`<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>`);
    }

    function infoMessage(divId, message) {
      $("#" + divId).empty();
      $("#" + divId).addClass("alert alert-info alert-dismissible");
      $("#" + divId).append(`<i class="fas fa-info-circle fa-lg"></i>`);
      $("#" + divId).append(`<strong> Heads Up!</strong> ${message}`);
      $("#" + divId).append(`<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>`);
    }

    function reIndexInput(totalDiv, divIdPrefix, divClass) {
        var i = 1;
        $("." + divClass).find(":input").each(function () {
            var prevName = $(this).attr('name');
            var newName = $(this).attr('name').replace(prevName, divIdPrefix + i)
            $(this).attr({ 'name': newName })
            i++;
        })
    }
    
    
  </script>
  {% endblock %}
  <!-- Custom Theme Scripts -->
  <script src="{% static 'custom/js/master.js' %}"></script>
  {% endblock body %}
</body>

</html>

inventory/templates/footer.html
<div class="pull-right">
    Powered by Udbhabok
</div>
<div class="clearfix"></div>

inventory/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="right_col">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12 center-margin">
            <div class="x_panel">
                <div class="x_title">
                    <div>
                        <h4>This is a test page</h4>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block javascripts %}
{{block.super}}
<script>
    $(document).ready(function() {
      
    });
</script>
{% endblock javascripts%}

inventory/templates/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="#" class="site_title"><i class="fas fa-layer-group"></i><span> Inventory</span></a>
  </div>

  <div class="clearfix"></div>

  <!-- sidebar menu -->
  <br />
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <ul class="nav side-menu">
        <li><a href="#"><i class='bx bx-grid-alt'></i> Dashboard </a></li>
        <li><a><i class="fas fa-archive"></i> Inventory <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'products:product-list' %}">Products</a></li>
            <li><a href="{% url 'products:product-type-list' %}">Product Type</a></li>
            <li><a href="{% url 'products:manage-stock' %}">Manage Stock</a></li>
          </ul>
        </li>
        <li><a><i class="fas fa-file-invoice"></i> Sales <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="#">New Invoice</a></li>
            <li><a href="#">Invoices</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>
<!-- /sidebar menu -->

inventory/templates/top_navigation.html
{% load static %}
<div class="nav_menu">
  <div class="nav toggle">
    <a id="menu_toggle"><i class="bx bx-menu"></i></a>
  </div>
  <nav class="nav navbar-nav">
    <!-- <ul class=" navbar-right">
      <li class="nav-item dropdown open" style="padding-left: 15px;">
        <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
        </a>
        <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"  href="3"> Profile</a>
          <a class="dropdown-item"  href="javascript:;">
            <span class="badge bg-red pull-right">50%</span>
            <span>Settings</span>
          </a>
          <a class="dropdown-item"  href="javascript:;">Help</a>
          <a class="dropdown-item"  href="#"><i class="fa fa-sign-out pull-right"></i> Logout</a>
        </div>
      </li>
      <li role="presentation" class="nav-item dropdown open mt-1">
        <a href="javascript:;" onClick="fetchNotificationsInBox();" class="dropdown-toggle info-number" id="navbar-dropdown-notifications" data-toggle="dropdown" aria-expanded="false">
          <i class="far fa-bell"></i>
          <span class="badge bg-green" id='new-notification-num'></span>
        </a>
        <ul id='notification-lst' class="dropdown-menu list-unstyled msg_list" role="menu" aria-labelledby="navbar-dropdown-notifications">
          <li class="nav-item">
            <a class="dropdown-item">
              <span class="image"><img src="/media/photo/img.jpg" alt="Profile Image" /></span>
              <span>
                <span>John Smith</span>
                <span class="time">3 mins ago</span>
              </span>
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li> 
           <li class="nav-item">
            <a class="dropdown-item">
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li> 
           <li class="nav-item">
            <div class="text-center">
              <a class="dropdown-item">
                <strong>See all notifications</strong>
                <i class="fa fa-angle-right"></i>
              </a>
            </div>
          </li>
        </ul>
      </li>
    </ul> -->
  </nav>
</div>